### ISSUE TITLE
Issue running Web-gui

### ISSUE THREAD

**Issue by jonny190** [malwaredllc/byob#426] opened 2021-03-16 00:22 UTC
### Please use the Discord Support Server if you need help and reserve creating issues for bug reports.

**Describe the bug**
Cannot start the web-gui 

**To Reproduce**
1. Installed fresh Ubuntu 20.04
2. Installed Python3-pip
3. Installed docker
4. Installed GIT
5. Cloned GIT
6. cd byob/web-gui
7. sudo ./startup.sh
8. sudo python3 run.py

**Expected behavior**
Run the Webui

**Screenshots**
![image](https://user-images.githubusercontent.com/8059327/111237663-79138d80-85ed-11eb-8d13-754f58288864.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version 3.8.5

**Comment by uyeet** [comment] 2021-03-16 18:25
JOIN THE DAMN DISCORD

**Comment by Cyberguardians101** [comment] 2021-03-16 19:55
@uyeet man your rude!! How do we do that!?

**Comment by fireFerry** [comment] 2021-03-17 18:08
A link to the discord can be found here: https://discord.gg/8FsSrw7

It's not neccesary to join the Discord, GitHub issues will also receive support.

**Comment by FieldOfRice** [comment] 2021-03-18 11:01
I've cloned the repo and afterwards added `SQLAlchemy==1.3.23` at the end of both requirements.txt. At least it's running for me after this change.

**Comment by malwaredllc** [comment] 2021-03-20 01:18
@FieldOfRice so you had this same issue, then after specifying `SQLAlchemy==1.3.23` the issue is resolved?

**Comment by malwaredllc** [comment] 2021-03-20 01:22
Found solution here https://stackoverflow.com/questions/52724793/flask-attributeerror-cant-set-attribute per tip from @FieldOfRice, fix will be included in my next PR I merge in.

**Closed** 2021-03-20 01:36 UTC
Labels: bug
